name: python3
builder:
  name: PythonBuilder
  flags: "no-make-dist relative-linking"
  configure_options: --enable-shared --enable-optimizations --enable-ipv6 --with-openssl=@@installdir@@
platforms:
  - linux-glibc2.11/amd64
